[[redirects]]
from = "/en/*"
to = "https://papercraft.tmat.me/book/:splat"
force = true
status = 301
conditions = { Host = ["handbook.tmat.me"] }

[[redirects]]
from = "/ru/*"
to = "https://papercraft.tmat.me/ru/book/:splat"
force = true
status = 301
conditions = { Host = ["handbook.tmat.me"] }

[[redirects]]
from = "*"
to = "https://papercraft.tmat.me/:splat"
force = true
status = 301
conditions = { Host = ["handbook.tmat.me"] }

[[redirects]]
from = "/book/*"
to = "/ru/book/:splat"
force = true
status = 302
conditions = { Language = ["ru"] }
